parameters:
    content_on_the_fly.default.content:
        image:
            location:
                - 51    # /Media/Images
                - 95    # /Vest Telemark/Bilder
        default:
            location:
                - 2     # /Home
                - 43    # /Media
                - 96   # /Vest Telemark/Filer